# Generated by Django 5.2.2 on 2025-06-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("preview_image", models.ImageField(upload_to="media/")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("views_counter", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Пост блога",
                "verbose_name_plural": "Посты блога",
            },
        ),
    ]
