# Generated by Django 5.2.3 on 2025-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_products_created_at_alter_products_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="views_counter",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
